### ISSUE TITLE
 Unresolved reference: Registrar

### ISSUE THREAD

**Issue by heshesh2010** [wrbl606/floating#27]
Hi ,

when build example folder  for android i got this error

e: file:///Users/heshamelnemr/.pub-cache/hosted/pub.dev/floating-5.0.0/android/src/main/kotlin/eu/wroblewscy/marcin/floating/floating/FloatingPlugin.kt:19:48 Unresolved reference: Registrar
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':floating:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel main, 3.27.0-1.0.pre.277, on macOS 15.0.1 24A348 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] VS Code (version 1.94.2)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

**Comment by wrbl606** [comment]
Does this issue also occurs on the stable Flutter branch for you? You are on `main` which I don't really plan to support.

**Comment by heshesh2010** [comment]
Only beta branch

**Comment by wrbl606** [comment]
Do you mean it works on the beta branch or doesn't?

**Comment by heshesh2010** [comment]
It’s works on stable but doesn’t work on beta channel

**Comment by wrbl606** [comment]
I can't confirm it doesn't work on the beta channel, tested on `3.27.0-0.1.pre` and the example app built and ran fine. Feel free to open a new issue if it still doesn't work for you.
